version: "3.9"
services:
  app-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "orders_db"
      - "orders_api"
      - "users_api"
      - "users_db"
    networks:
      - default
  users_api:
    build: https://github.com/Sugar-pack/users-manager.git#main
    ports:
      - "8082:8080"
    depends_on:
      - "users_db"
    networks:
      - default
  users_db:
    image: "postgres:14.2"
    ports:
      - "15432:5432"
    networks:
      - default
    hostname: users_db
    command:
      - --max_prepared_transactions=100
    environment:
      POSTGRES_USER: user_db
      POSTGRES_DB: users_db
      POSTGRES_HOST_AUTH_METHOD: trust
  orders_api:
    build: https://github.com/Sugar-pack/orders-manager.git#main
    ports:
      - "8081:8080"
    depends_on:
      - "orders_db"
    networks:
      - default
  orders_db:
    image: "postgres:14.2"
    ports:
      - "15433:5432"
    networks:
      - default
    hostname: orders_db
    command:
      - --max_prepared_transactions=100
    environment:
      POSTGRES_USER: user_db
      POSTGRES_DB: orders
      POSTGRES_HOST_AUTH_METHOD: trust

