version: "3.9"
services:
  app-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "orders_db"
      - "orders_api"
      - "users_api"
      - "users_db"
    networks:
      - default
    environment:
      - OTEL_SERVICE_NAME=app-service
      # Found these variables here https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger#section-readme
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger-agent
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-tracing:14268/api/traces
  users_api:
    build: https://github.com/Sugar-pack/users-manager.git#main
    ports:
      - "8082:8080"
    depends_on:
      - "users_db"
    networks:
      - default
    environment:
      - OTEL_SERVICE_NAME=users-api
      # Found these variables here https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger#section-readme
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger-agent
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-tracing:14268/api/traces
  users_db:
    image: "postgres:14.2"
    ports:
      - "15432:5432"
    networks:
      - default
    hostname: users_db
    command:
      - --max_prepared_transactions=100
    environment:
      POSTGRES_USER: user_db
      POSTGRES_DB: users_db
      POSTGRES_HOST_AUTH_METHOD: trust
  orders_api:
    build: https://github.com/Sugar-pack/orders-manager.git#main
    ports:
      - "8081:8080"
    depends_on:
      - "orders_db"
    networks:
      - default
    environment:
      - OTEL_SERVICE_NAME=orders-api
      # Found these variables here https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger#section-readme
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger-agent
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-tracing:14268/api/traces
  orders_db:
    image: "postgres:14.2"
    ports:
      - "15433:5432"
    networks:
      - default
    hostname: orders_db
    command:
      - --max_prepared_transactions=100
    environment:
      POSTGRES_USER: user_db
      POSTGRES_DB: orders
      POSTGRES_HOST_AUTH_METHOD: trust
  resp_cache:
    image: "redis:6.2"
    ports:
      - "16379:6379"
    networks:
      - default
    hostname: response_cache
  server-tracing:
    image: "jaegertracing/all-in-one:1.33"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - default
    hostname: jaeger-tracing
