definitions:
  webapi.Message:
    properties:
      label:
        example: Bag
        type: string
      name:
        example: John
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server.
  title: Server Example
  version: "0.1"
paths:
  /send:
    post:
      consumes:
      - application/json
      description: Put message with name and label to DB by 2pc transactions
      parameters:
      - description: Message
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/webapi.Message'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: message decode error
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      summary: Send message
      tags:
      - accounts
swagger: "2.0"
