name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOLANG_VERSION: '1.18'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Build
        run: make build